services:
  gcc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./_bash_history:/root/.bash_history
      - ../roc-toolkit:/workspace/roc-toolkit
    tty: true
    stdin_open: true
